### ISSUE TITLE
Ausführung subprocess geht nicht

### ISSUE THREAD

**Issue by vansen** [geronet1/mbus-test#1]
Hallo, erstmal vielen Dank für die Bereitstellung. Ich hab den Link aus dem Haustechnikforum. Ich kämpfe mit dem auslesen über MBUS und IR Schnittstelle von meine Sensostar Wärmezähler. Ich bin mir nicht sicher, ob ich auf dem weg vom Repository über den Build bis zur Ausführung nen Fehler habe, aber bei schlägt das python script fehl. Ich habe folgendes gemacht:
- git clone deines repos
- im Release folder "make" ausgeführt. Daraufhin wurde unter anderem die Datei mbus-test erzeugt: 
![image](https://user-images.githubusercontent.com/13270526/211106002-6df92b8e-1705-40a5-9bbb-7b30b58d0fe8.png)
- gehe ich jetzt einen Ordner höher und führe das python script aus: "python3 readout-test.py"
- Dann zeigt er den start an, die nächste Zeile mit dem last update und dann kommt es nach dem timeout zu folgendem Fehler: 
![image](https://user-images.githubusercontent.com/13270526/211106285-ba32853a-a33d-40a6-9034-c14e6636fc12.png)
Er müsste das Ziel im subprocess ja ausführen, dabei gibt es wohl einen Fehler. 
Wenn ich die Datei manuell versuche auszuführen, geht leider auch nicht. Da sagt er mir er kann die Datei nicht finden.

Irgendeine Idee was ich falsch mache, ich hoffe du kannst mir einen Tipp geben. 
Danke schonmal, 
Oliver

**Comment by geronet1** [comment]
Hi,
das readout-test.py war eigentlich nur ein Testscript, du muss die Datei direkt ausführen:

cd Release
./mbus-test

**Comment by vansen** [comment]
Danke!
